server:
  port: 9000
cloud:
  aws:
    s3:
      bucket: hyunnbucket
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: AKIAU65GIVE2VGO7JUU3
      secretKey: 
spring:
  application:
    name: carrot
  profiles:
    active: dev # default profile
  datasource:
    url: jdbc:mysql://hyunndb.cuq9ijf7omb7.ap-northeast-2.rds.amazonaws.com/carrot?autoReconnect=true
    username: master
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 33807763033-0v5cprhe2e10lablr41a6jsctuorifr7.apps.googleusercontent.com
            client-secret: 
            redirect-uri: http://localhost:9000/login/oauth2/code/google
            scope: email
          naver:
            client-id: tGYxbLNA164pXlARLhx3
            client-secret:
            redirect-uri: http://localhost:9000/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: email
            client-name: Naver
          kakao:
            client-id: 2b018bbff06bbad2999336e04c23e9cd
            client-secret:
            redirect-uri: http://localhost:9000/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            scope: account_email
            client-name: Kakao
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
