server:
  port: 8888
cloud:
  aws:
    s3:
      bucket: hyunnbucket
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey:
      secretKey:
spring:
  application:
    name: carrot
  profiles:
    active: dev # default profile
  datasource:
    url: jdbc:mysql://hyunndb.cuq9ijf7omb7.ap-northeast-2.rds.amazonaws.com/carrot?autoReconnect=true
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            redirect-uri: https://carrot.hyunn.shop/login/oauth2/code/google
            scope: email
          naver:
            client-id:
            client-secret:
            redirect-uri: https://carrot.hyunn.shop/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: email
            client-name: Naver
          kakao:
            client-id:
            client-secret:
            redirect-uri: https://carrot.hyunn.shop/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            scope: account_email
            client-name: Kakao
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
