server:
  port: 9000
spring:
  application:
    name: carrot
  profiles:
    active: dev # default profile
  datasource:
    url: jdbc:mysql://hyunndb.cuq9ijf7omb7.ap-northeast-2.rds.amazonaws.com/carrot?autoReconnect=true
    username: master
    password: ht991202!
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 33807763033-0v5cprhe2e10lablr41a6jsctuorifr7.apps.googleusercontent.com
            client-secret: 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
            scope: email
          naver:
            client-id: tGYxbLNA164pXlARLhx3
            client-secret: xacId9VXIF
            redirect-uri: https://carrot.hyunn.shop/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: email
            client-name: Naver
          kakao:
            client-id: 2b018bbff06bbad2999336e04c23e9cd
            client-secret: bLrsb7rclrg1VWjBkgIjGdJ5JABKJ9ug
            redirect-uri: https://carrot.hyunn.shop/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            scope: account_email
            client-name: Kakao
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
